# Site settings
title: "Dhruvajyoth Kommuri Profile"
description: "Profile of Dhruvajyoth Kommuri"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dhruvajyoth Kommuri"
resume_title:                   "Java Full Stack Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dhruvajyothk@outlook.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+1(819)919-5415"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "+1(819)919-5415 • dhruvajyothk@outlook.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>
• Around 7 years of professional experience in Cross-Platform (Web & Client-Server) application 
 development and design using Object-Oriented Programming, Core Java, and J2EE technologies.<br>
• Experience working in environments using Agile (SCRUM) and Test-Driven development (TDD) 
 methodologies.<br>
• Expertise in java 8 features such as Lambdas, Parallel Streams, filters & functional interfaces.<br>
• Experience working on front end technologies - Angular and React JS.<br>
• Have strong exposure and work experience on core java concepts collection API, Stream API, Parallel 
 Streams, exception handling, Multithreading, HashMap, concurrency, JDBC, modularity, executor service, 
 fork and join frameworks.<br>
• Strong understanding of Microservices patterns -Hystrix, Aggregator, Proxy chaining.<br>
• Implemented various Design patterns (Session Façade, Value Object, DAO, DTO, Command, Singleton, 
 Factory, Adapter, MVC, Service Locator etc.) using J2EE technologies.<br>
• Strong experience in Spring modules -Spring MVC, IOC, AOP, JDBC, JTA, IO, Spring Boot, Spring 
 Microservices, Spring REST.<br>
• Strong experience on Restful APIs & SOAP web services.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/dhruvajyoth-kommuri-49425a26a/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://dhruvajyothk.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
